/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/amankumar/Desktop/akportfolio/public/classic_tv.glb --types 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
    DialSmall: THREE.Mesh;
    Grill: THREE.Mesh;
    DialBig: THREE.Mesh;
    BottomRest: THREE.Mesh;
  };
  materials: {
    MaterialFrame: THREE.MeshPhysicalMaterial;
    MaterialScreen: THREE.MeshStandardMaterial;
    MaterialSmallDial: THREE.MeshStandardMaterial;
    MaterialBigDial: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function ClassicTv(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/classic_tv.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <group
        position={[-0.292, -0.598, 0.817]}
        rotation={[0.005, 0, 0]}
        scale={[3.771, 2.051, 2.051]}
      >
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.MaterialFrame}
        />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials.MaterialScreen}
        />
      </group>
      <mesh
        geometry={nodes.DialSmall.geometry}
        material={materials.MaterialSmallDial}
        position={[2.636, 2.281, 2.716]}
        rotation={[1.576, 0, 0]}
        scale={0.337}
      />
      <mesh
        geometry={nodes.Grill.geometry}
        material={nodes.Grill.material}
        position={[2.641, 1.6, 2.545]}
        rotation={[0.005, 0, 0]}
        scale={2.051}
      />
      <mesh
        geometry={nodes.DialBig.geometry}
        material={materials.MaterialBigDial}
        position={[2.611, 3.2, 2.768]}
        rotation={[1.576, 0.703, 0]}
        scale={0.441}
      />
      <mesh
        geometry={nodes.BottomRest.geometry}
        material={materials.MaterialFrame}
        position={[-0.292, -0.598, 0.817]}
        rotation={[0.005, 0, 0]}
        scale={2.051}
      />
    </group>
  );
}

useGLTF.preload("/models/classic_tv.glb");
